name: Esteira CI/CD Python baseado em GitHub Actions
on:
    push:
      branches: [feature/esteira]
      
jobs:
  setupEnvironment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requeriments.txt